---
title: "Mysql"
date: 2017-09-03T09:38:54-03:00
draft: true
---



# Banco de Dados

- Arquivos

- Tabelas

- Registros

- Arquivos Sequenciais X Arquivos Acesso Direto X Banco de dados

#SQL (Structured Query Language)

- Pagos: Oracle, IBM, dBASE, Microsoft SQL Server

- Grátis: MySql, MariaDB,...

# MySql

- Criado em 1994 na Suécia

- Michael Widenius e David Axmark

- É livre 

- Atualmente pertence à Oracle

- Nasa, Google, Adobe, Ebay, Bradesco, Telecomunicação,...

# Criando o Primeiro Banco de Dados

Banco de dados -> Tabelas -> Registros -> Campos

Criando o Banco de Dados:

```
CREATE DATABASE cadastro;
```



Tipos primitivos de dados:

1. Numérico: 
  
    - Inteiro: TinyInt, SmallInt, Int, MediumInt, BigInt
    
    - Real: Decimal, Float, Double, Real
    
    - Lógico: Bit, Bolean
  
2. Data/Tempo: Date, DateTime, TimeStamp, Time, Year
  
3. Literal: 

    - Caractere: Char (Tamanho Fixo), VarChar (Se adapta a palavra)
    
    - Textos(textos longos): TinyText, Text, MediumText, LongText
    
    - Binário: TinyBlob, Bob, MediumBlob, LongBlob
    
    - Coleção: Enum, Set
  
4. Espacial: Geometry, Point, Polygon, MultiPolygon

Criando a Tabela:

```
CREATE TABLE pessoas (
nome varchar(30),
idade tinyint(3),
sexo char(1),
peso float,
altura float,
nacionalidade varchar(20)
);
```

Visualizando a tabela:

```
DESCRIBE pessoas;
```

# Melhorando o nosso banco de dados

Deletando o banco de dados anterior:

```
DROP DATABASE cadastro;
```

Criando o BD melhorado:

```
CREATE DATABASE cadastro
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;
```

Criando a Tabela Melhorada:

```
CREATE TABLE pessoas (

id int NOT NULL AUTO_INCREMENT,
nome varchar(30) NOT NULL,
nascimento date,
sexo ENUM("M", "F"),
peso decimal(5,2),
altura decimal(3,2),
nacionalidade varchar(20) DEFAULT "Brasil",
PRIMARY KEY(id)

) DEFAULT CHARSET = utf8;
```

# Inserindo Dados na Tabela

Inserindo os dados:

```
INSERT INTO pessoas (nome, nascimento, sexo, peso, altura, nacionalidade) VALUES ('Guilherme','1996-01-20','M','75.10','1.84','Brasil');
```

Inserindo Vários dados ao mesmo tempo:

```
INSERT INTO pessoas (nome, nascimento, sexo, peso, altura, nacionalidade) VALUES ('Luiz','1986-01-20','M','72.10','1.84','Portugal'),
('Jośe','1955-01-20','M','100.20','1.94','Irlanda');
```

Verificando se foi inserido:

```
SELECT * FROM pessoas;
```
# Alterando a Estrutura da Tabela

Adicionando nova coluna:

```
ALTER TABLE pessoas ADD COLUMN profissao varchar(10);
```
Eliminar uma coluna:

```
ALTER TABLE pessoas DROP COLUMN profissao;
```

Adicionando coluna entre colunas:

```
ALTER TABLE pessoas ADD COLUMN profissao varchar(10) AFTER nome;
```

Alterando a estrutura da coluna:

```
ALTER TABLE pessoas MODIFY COLUMN profissao varchar(20); 
```

Renomear uma coluna:

```
ALTER TABLE pessoas CHANGE COLUMN profissao prof varchar(15);
```

Renomear o nome da tabela:

```
ALTER TABLE pessoas RENAME TO dados;
```

Criando a tabela cursos:

```
CREATE TABLE IF NOT EXISTS cursos(
  nome varchar(30) NOT NULL UNIQUE,
  descricao text,
  carga int UNSIGNED,
  totaulas int,
  ano year DEFAULT '2016'
) DEFAULT CHARSET = utf8;
```

Adicionando o campo de chave primaria:

```
ALTER TABLE cursos ADD COLUMN idcurso int FIRST;
ALTER TABLE cursos ADD PRIMARY KEY(idcurso);
```

Excluindo a tabela:

```
DROP TABLE tabela;
```

# Manipulando linhas

Adicionando valores na tabela curso para serem modificadas:

```
INSERT INTO cursos VALUES
 ('1','HTML4','Curso de HTML5', '40','37','2014'),
    ('2','Algoritmos','Lógica de Programação','20','15','2014'),
    ('3','Photoshop','Dicas de Photoshop CC','10','8','2014'),
    ('4','PGP','Curso de PHP para iniciantes','40','20','2010'),
    ('5','Jarva','Introdução à Linguagem Java','10','29','2000'),
    ('6','MySQL','Banco de Dados MySQL','30','15','2016'),
    ('7','Word','Curso completo de Word','40','30','2016'),
    ('8','Sapateado','Danças Rítmicas','40','30','2018'),
    ('9','Cozinha Árabe','Aprenda a fazer Kibe','40','30','2018'),
    ('10','Youtuber','Gerar polêmica e ganhar inscritos','5','2','2018');
```

Modificando as linhas erradas:

```
UPDATE cursos SET nome = 'HTML5' WHERE idcurso = '1';
UPDATE cursos SET nome = 'PHP', ano = '2015' WHERE idcurso = '4';
UPDATE cursos SET nome = 'Java', carga = '40', ano = '2015' WHERE idcurso = '5' LIMIT 1;
UPDATE cursos SET ano = '2015' WHERE ano = '2018';
```

Deletando linhas:

```
DELETE FROM cursos WHERE idcurso = '8';
DELETE FROM cursos WHERE idcurso = '9';
DELETE FROM cursos WHERE idcurso = '10';
```

Deletando Todas as linhas de uma tabela:

```
TRUNCATE TABLE cursos;
```


# Obtendo Dados das Tabelas

Selecionando todos os dados:

```
SELECT * FROM cursos;
```

Ordenação Crescente:

```
SELECT * FROM cursos ORDER BY nome;
```

Ordenação Decrescente:

```
SELECT * FROM cursos ORDER BY nome DESC;
```

Selecionando Colunas:

```
SELECT nome, carga, ano FROM cursos ORDER BY nome;
```

Selecionando Linhas:

```
SELECT * FROM cursos WHERE ano = '2016' ORDER BY nome DESC;
```

Selecionando Linhas e Colunas:

```
SELECT nome, descricao FROM cursos WHERE ano = '2016' ORDER BY nome DESC;
SELECT nome, descricao FROM cursos WHERE ano != '2016' ORDER BY nome DESC;
SELECT nome, descricao FROM cursos WHERE ano > '2016' ORDER BY nome DESC;
SELECT nome, descricao FROM cursos WHERE ano between 2014 and 2016;
SELECT nome, descricao FROM cursos WHERE ano IN ('2014', '2016');
```

Selecionando todos os cursos que começam com a letra P:

```
SELECT * FROM cursos WHERE nome LIKE 'P%';
```

Selecionando todos os cursos que terminam com a letra A:

```
SELECT * FROM cursos WHERE nome LIKE '%A';
```

Selecionando os cursos que não possuem a letra A:

```
SELECT * FROM cursos WHERE nome NOT LIKE '%A%';
```

Lista com as cargas horarias:

```
SELECT DISTINCT carga FROM cursos;
```

Contando itens:

```
SELECT  COUNT(*) FROM cursos where carga > 40;
```

Maximo, minimo, soma e media de uma campo:

```
SELECT  MAX(carga) FROM cursos;
SELECT  MIN(carga) FROM cursos;
SELECT  SUM(carga) FROM cursos WHERE ano = '2016';
SELECT  AVG(carga) FROM cursos;
```

Agrupando registros:

```
SELECT carga FROM cursos GROUP BY carga;
SELECT carga, COUNT(nome) FROM cursos GROUP BY carga;
```

Agrupando e agregando:

```
SELECT ano, COUNT(nome) FROM cursos GROUP BY ano HAVING COUNT(ano) >= 5;
SELECT carga, COUNT(nome) FROM cursos WHERE ano > 2015 GROUP BY carga HAVING carga > (SELECT AVG(carga) FROM cursos);
```

# Modelo Relacional

Chaves Estrangeiras:

Usada para relacionar tabelas

```
#Adicionando o curso preferido na tabela alunos
##Criando a coluna cursopreferido

ALTER TABLE alunos ADD COLUMN cursopreferido int;


#Informando que a coluna cursopreferido é uma chave estrangeira

ALTER TABLE alunos ADD FOREIGN KEY (cursopreferido) REFERENCES cursos(idcurso);

#Adicionando o curso preferido de cada aluno

UPDATE alunos SET cursopreferido = '6' WHERE id = '1';

#Mostrando os cursos preferidos

SELECT alunos.nome, cursos.nome, cursos.ano  FROM alunos JOIN cursos on cursos.idcurso = alunos.cursopreferido;

```

#Usando o pacote RMySQL

```{r, warning=FALSE, eval=FALSE}
library(RMySQL)

#Conectando com o Bd

con <- dbConnect(MySQL(),
                 user="root", password="root",
                 dbname="cadastro", host="127.0.0.1")

#Lista com todas as tabelas do nosso Bd

dbListTables(con)

#Criando uma tabela nova

dbWriteTable(con, "novatabela", mtcars)

#Lendo a tabela do Bd

head( dbReadTable(con, "novatabela"))

#Fazendo uma Query usando SQL

dbGetQuery(con, "SELECT * FROM novatabela limit 5")

dbGetQuery(con, "ALTER TABLE novatabela RENAME TO carros")

dbListTables(con)

#Excluindo a tabela:

dbRemoveTable(con, "carros")
```